name: Test Event Log Calculation

on:
  pull_request:
    branches:
      - main
      # Add more branches as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and compare output
      run: python test_sccript.py

    - name: Compare output
    #   run: python compare_output.py
      run: diff output.json expected_output.json
    
