name: Test Event Log Calculation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and compare output
      run: |
        python test_sccript.py
        if cmp -s output.json expected_output.json; then
          echo "Outputs are identical. Proceeding with merge."
          exit 0
        else
          echo "Outputs are different. Merge blocked."
          exit 1
        fi

    - name: Merge branch (if outputs are same)
      if: ${{ success() }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          console.log(result.data);

